apiVersion: v1
data:
  paymybuddy_db_password: dG90bwo= 
  mysql_password: dG90bwo=
  mysql_random_root_password: MQo= 
kind: Secret
metadata:
  name: app-paymybuddy-secret
  namespace: paymybuddy
type: Opaque