apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy
  labels:
    app: paymybuddy
  namespace: paymybuddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymybuddy
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paymybuddy
        tier: frontend
    spec:
      containers:
      - image: olivierkkoc/paymybuddy:latest
        name: paymybuddy
        env:
        - name: SPRING_DATASOURCE_USERNAME
          value: eazytraining
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql/db_paymybuddy
        - name: SPRING_DATASOURCE_DB_HOST
          value: mysql
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-paymybuddy-secret
              key: paymybuddy_db_password
        ports:
        - containerPort: 8080
          name: paymybuddy