apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy-mysql
  labels:
    app: paymybuddy
  namespace: paymybuddy
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: paymybuddy
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: paymybuddy
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: paymybuddy
        - name: MYSQL_USER
          value: eazytraining
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-paymybuddy-secret
              key: mysql_password
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-paymybuddy-secret
              key: mysql_random_root_password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: /data/mysql
